config/routes.rb
Rails.application.routes.draw do


  resources :invitations, except: %i(new edit, show)

  resources :password_resets

  resources :restaurants, only: %i(index)

  root 'homes#index'

  get 'login' => 'sessions#new', :as => :login
  post 'create' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', :as => :logout
  get 'game' => 'pictures#index', :as => :game

  resources :homes, only: %i(index)
  #  will this work we shalll see
  resources :votes, except: %i(destroy)

    delete 'votes' => 'votes#destroy'


  resources :tags, except: %i(destroy edit update)
  resources :users, except: %i(destroy)
  resources :pictures, except: %i(index)

  namespace :admin do
    resources :pictures
  end

  namespace :user do
      resources :cuisines, only: %i(index show)
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :first_name, :last_name, :address, presence: true

  validates :age, :inclusion => { :in => 1..100, :message => "Age should be between 1-100"}


  # validate :age_range

# Mounting Uploader for ProfilePic

  mount_uploader :profile_pic, ProfilePicUploader


# adding geolocation

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # everytime we add a restaurant we want to geocode it. User.near("220 King Street")


  has_many :votes
  has_many :pictures, through: :votes
  has_many :tags, through: :pictures
  has_many :cuisines, through: :pictures
  has_many :sent_invitations, class_name: 'Invitation', foreign_key: :send_user_id
  has_many :accepted_invitations, class_name: 'Invitation', foreign_key: :accept_user_id



  def top_cats
    category_arr = []
    pics = self.pictures


    pics.each do |pic|
      cat = pic.cuisine
      category_arr << cat.name
    end
    category_arr

    cat_hash = Hash.new(0)

    category_arr.each do |key|
      cat_hash[key] += 1
    end

    cat_hash.sort_by {|k,v| v}.reverse.take(3)
  end

  def top_tags
    tag_arr = []
    pics = self.pictures


    pics.each do |pic|
      tag = pic.tags
      tag.each do |i|
        tag_arr << i.name
      end
    end
    tag_arr

    tag_hash = Hash.new(0)

    tag_arr.each do |key|
      tag_hash[key] += 1
    end

    tag_hash.sort_by {|k,v| v}.reverse.take(4)
  end

  def inv_arr
    sent_invites = self.sent_invitations
    accept_invites = self.accepted_invitations

    all_invites = sent_invites + accept_invites
  end





end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def index
    @cuisines = Cuisine.all

    respond_to do |format|
      format.html
      format.js
    end

  end

  def show
  end

  def new
  end

  def create
  end
end

app/controllers/user/cuisines_controller.rb
class User::CuisinesController < ApplicationController
  def index
    @cuisines = Cuisine.all


    respond_to do |format|
      format.html
      format.js
    end

  end

  def show
    @cuisine = Cuisine.find(params[:id])
  end

  def new
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index

    @cuis = params[:category]
    potentials = []
    array_users = User.where(down_to_meet: true)
    invites_arr = current_user.inv_arr


    array_users.each do |user|
      if user.top_cats.empty?
        next
      else
        cuisine_A = user.top_cats
        if cuisine_A[0].include?(@cuis)
          potentials << user.id
        elsif cuisine_A[1].include?(@cuis)
          potentials << user.id
        elsif cuisine_A[2].include?(@cuis)
          potentials << user.id
        else
        end
      end
    end

    inv_id = []
    potentials.each do |id|
      invites_arr.each do |inv|
        if (inv.send_user_id == current_user.id && inv.accept_user_id == id) || (inv.accept_user_id == current_user.id && inv.send_user_id == id)
          invites_arr.delete(inv)
          inv_id << id
        end
      end
    end

    inv_id.each do |id|
      potentials.delete(id)
    end
    potentials.delete(current_user.id)
    @users = []

    potentials.each do |id|
      @users << User.find(id)
    end


    if request.xhr?
      render partial: 'users'
    end
  end



  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)


    if @user.save
      auto_login(@user)

      UserMailer.welcome_email(@user).deliver_later

      redirect_to root_url :notice => "signed up!"

    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])

      # respond_to do |format|
      #   format.js
      #   format.html
      # end

  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)
    if @user.update_attributes(user_params_edit)
      if request.xhr?
        render nothing: :true
      else
        render :show
      end
    else
      render :edit
    end
  end

  private
  def user_params_edit
    params.require(:user).permit(:first_name, :last_name, :username, :email, :address, :phone_number, :latitude, :longitude, :profile_pic, :bio, :age, :down_to_meet)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_name, :email, :address, :age, :phone_number, :password, :password_confirmation)
  end
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/cuisines/index.html.erb
<div class="container" id="results-page">

    <div class="top-cuis">
      <h1>Here are your top three cuisines... </h1>
      <p style="font-size: 1.4rem">See nearby restaurants that match your cuisines and/or find yourself a Dindr date!</p>
    </div>


    <!-- List Bullet Cards-->

    <div id="results-card-container">

      <ul id="results-card-set">
      <% current_user.top_cats.each do |cat| %>
        <li class="card">
          <div class='icon'><%= image_tag('food-love.png') %></div>
          <h1><%= cat[0] %></h1>
          <p>Mmm Delish!</p>
          <%= button_tag "Find Restaurants", class:"nearby-restaurants", id:"show-rests-button", data: {cuisinelabel:  "#{@cuisines.find_by(name: cat[0]).label}"}  %>

          <!-- <#%= button_to "Find Restaurants", restaurants_path, method: :get, class:"nearby-restaurants", data: {cuisinelabel:  "#{@cuisines.find_by(name: cat[0]).label}"}  %> -->
          <% if current_user.profile_pic? == false %>
            <div class="">
              <%= link_to "change profile pic to dindr", edit_user_path(current_user.id), id:"no-prof"%>
            </div>
          <% else %>
            <%= button_tag "Find A Date!", class:"dindr-dates", id:"show-date-button", data: {cuisinename: cat[0]} %>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>

    <!-- Play Again Button -->

    <div id="reset-pics-button" >
      <%= button_to "Play Again", :game, method: :get, id:"play-again-button"%>
    </div>

    <div class="result-restaurants-dates" >
    </div>


</div>

app/views/user/cuisines/show.html.erb
<div class="container" id="date-page">
<!-- Potentially have to put this all into a cuisines controller of its own -->
<!-- Instead of applying this into the user/cuisines... have it in its own route and model -->
  <div class="cuisine-title">
    <h1>Find a Dindr Guest/Date for...</h1>
    <h2><%= @cuisine.name %>!</h2>
  </div>











</div>