config/routes.rb
Rails.application.routes.draw do


  resources :invitations, except: %i(new edit, show)

  resources :password_resets

  resources :restaurants, only: %i(index)

  root 'homes#index'

  get 'login' => 'sessions#new', :as => :login
  post 'create' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', :as => :logout
  get 'game' => 'pictures#index', :as => :game

  resources :homes, only: %i(index)
  #  will this work we shalll see
  resources :votes, except: %i(destroy)

    delete 'votes' => 'votes#destroy'


  resources :tags, except: %i(destroy edit update)
  resources :users, except: %i(destroy)
  resources :pictures, except: %i(index)

  namespace :admin do
    resources :pictures
  end

  namespace :user do
      resources :cuisines, only: %i(index show)
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :first_name, :last_name, :address, presence: true

  validates :age, :inclusion => { :in => 1..100, :message => "Age should be between 1-100"}


  # validate :age_range

# Mounting Uploader for ProfilePic

  mount_uploader :profile_pic, ProfilePicUploader


# adding geolocation

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # everytime we add a restaurant we want to geocode it. User.near("220 King Street")


  has_many :votes
  has_many :pictures, through: :votes
  has_many :tags, through: :pictures
  has_many :cuisines, through: :pictures
  has_many :sent_invitations, class_name: 'Invitation', foreign_key: :send_user_id
  has_many :accepted_invitations, class_name: 'Invitation', foreign_key: :accept_user_id



  def top_cats
    category_arr = []
    pics = self.pictures


    pics.each do |pic|
      cat = pic.cuisine
      category_arr << cat.name
    end
    category_arr

    cat_hash = Hash.new(0)

    category_arr.each do |key|
      cat_hash[key] += 1
    end

    cat_hash.sort_by {|k,v| v}.reverse.take(3)
  end

  def top_tags
    tag_arr = []
    pics = self.pictures


    pics.each do |pic|
      tag = pic.tags
      tag.each do |i|
        tag_arr << i.name
      end
    end
    tag_arr

    tag_hash = Hash.new(0)

    tag_arr.each do |key|
      tag_hash[key] += 1
    end

    tag_hash.sort_by {|k,v| v}.reverse.take(4)
  end

  def inv_arr
    sent_invites = self.sent_invitations
    accept_invites = self.accepted_invitations

    all_invites = sent_invites + accept_invites
  end





end

app/controllers/user/cuisines_controller.rb
class User::CuisinesController < ApplicationController
  def index
    @cuisines = Cuisine.all


    respond_to do |format|
      format.html
      format.js
    end

  end

  def show
    @cuisine = Cuisine.find(params[:id])
  end

  def new
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index

    @cuis = params[:category]
    potentials = []
    array_users = User.where(down_to_meet: true)
    invites_arr = current_user.inv_arr


    array_users.each do |user|
      if user.top_cats.empty?
        next
      else
        cuisine_A = user.top_cats
        if cuisine_A[0].include?(@cuis)
          potentials << user.id
        elsif cuisine_A[1].include?(@cuis)
          potentials << user.id
        elsif cuisine_A[2].include?(@cuis)
          potentials << user.id
        else
        end
      end
    end

    inv_id = []
    potentials.each do |id|
      invites_arr.each do |inv|
        if (inv.send_user_id == current_user.id && inv.accept_user_id == id) || (inv.accept_user_id == current_user.id && inv.send_user_id == id)
          invites_arr.delete(inv)
          inv_id << id
        end
      end
    end

    inv_id.each do |id|
      potentials.delete(id)
    end
    potentials.delete(current_user.id)
    @users = []

    potentials.each do |id|
      @users << User.find(id)
    end


    if request.xhr?
      render partial: 'users'
    end
  end



  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)


    if @user.save
      auto_login(@user)

      UserMailer.welcome_email(@user).deliver_later

      redirect_to root_url :notice => "signed up!"

    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])

      # respond_to do |format|
      #   format.js
      #   format.html
      # end

  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)
    if @user.update_attributes(user_params_edit)
      if request.xhr?
        render nothing: :true
      else
        render :show
      end
    else
      render :edit
    end
  end

  private
  def user_params_edit
    params.require(:user).permit(:first_name, :last_name, :username, :email, :address, :phone_number, :latitude, :longitude, :profile_pic, :bio, :age, :down_to_meet)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_name, :email, :address, :age, :phone_number, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_users.html.erb
<% if @users.empty? %>
  <h1>Sorry no users are craving <%=@cuis %>!</h1>
<% else %>
<div class="dindr-date-results">
  <h1>Others craving <%=@cuis%>!</h1>


<!-- <div class="dindr-date-layout"> -->

  <div >
    <ul>
      <div class="potential-list">
        <% @users.each do |user| %>
        <!-- <div class="dindr-date-box" data-acceptuserName='<#%= user.first_name %>'></div> -->
            <li class="potential-dates" data-acceptuserName='<%= user.first_name %>'>
              <div class="pro-pic">
                <%= image_tag user.profile_pic.url, class: "dindr-date-pic", data: {datecuisine: "#{@cuis}", acceptuserId: user.id, acceptuserName: user.first_name, currentuserid: current_user.id } %>
              </div>
              <div class="summary" data-acceptuserName='<%= user.first_name %>'>
                <%= link_to User.find(user.id).first_name, user_path(user.id), :target => "_blank" %>, <%= user.age %>
              </div>
              <div class="choice">
                <button type="button" name="button" class="send_invite" id="show-rests-button" data-datecuisine=<%= @cuis %> data-acceptuserId=<%= user.id %> data-acceptuserName=<%= user.first_name %> data-currentuserid=<%= current_user.id %> >Send Invite!</button>
                <button type="button" name="button" class="delete_selection" id="show-date-button">Nope!</button>
              </div>
            </li>
        <% end %>
      </div>
    </ul>
  </div>
<% end %>



<!-- </div> -->

  <div id="dindr-date-profiles">
    <%= button_to "See Invitations", invitations_path,  method: :get, id:"see-invitations-button"%>
  </div>

</div>

app/views/users/edit.html.erb
<div class='container' id='edit-user-page'>
  <h1>Edit Profile</h1>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    <% end %>

    <div class="profile-pic">
      <%= f.label :Profile_Picture %>
      <%= f.file_field :profile_pic %>
    </div>

    <div class="edit-user-ubio">
      <%= f.label :bio %><br>
      <%= f.text_field :bio %>
    </div>

    <div class="edit-user-uage">
      <%= f.label :age %><br>
      <%= f.number_field :age %>
    </div>


    <div class="edit-user-uname">
      <%= f.label :user_name %><br>
      <%= f.text_field :user_name %>
    </div>

    <div class="edit-user-fname">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>

    <div class="edit-user-lname">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>

    <div class="edit-user-email">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </div>

    <div class="edit-user-phone">
      <%= f.label :phone_number %><br>
      <%= f.telephone_field :phone_number %>
    </div>

    <div class="edit-user-address">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>

    <div class="edit-user-button">
       <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/users/new.html.erb
<div class="container" id="new-user-page">
  <h1>Sign Up!</h1>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Please refill the form!</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :user_name %>
      <%= f.text_field :user_name %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <%= f.label :age %><br>
      <%= f.number_field :age %>
    </div>
    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :phone_number %>
      <%= f.telephone_field :phone_number %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="action">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<!-- Nav 2 -->

<%= render 'layouts/homepage_navbar' %>

<div class="container" id="profile-page">

  <div id="profile-card-container">
    <ul id="profile-card-set">
      <li id="profile-card">

        <div id='profile-icon'><%= image_tag @user.profile_pic.url%></div>

        <h1><%= @user.first_name %> <%= @user.last_name %></h1>

        <p>Dindr'ing since: <%= @user.created_at.to_date.strftime("%B %d, %Y") %></p>

        <p>Age: <%= @user.age %></p>
        <p>About Me: <%= @user.bio %> Blah blah blah for now</p></br>

        <p>

          <em><strong>Down to Dindr?</strong></em>
          <div id="down_to_meet">
            <% if @user.profile_pic? == false %>
              You must have a profile picture to change this setting!
            <% elsif @user.down_to_meet == true  %>
              Yes! Let's Eat!
            <% else %>
              Nah, I'm good.
            <% end %>
          </div>

          <% if current_user.id == @user.id && @user.profile_pic? %>
            <% if @user.down_to_meet == true %>
              <div class="toggle-button selected" data: {useid: current_user.id}>
                  <button>

                  </button>
              </div>
            <% else %>
              <div class="toggle-button" data: {useid: current_user.id}>
                  <button>

                  </button>
              </div>
            <% end %>
          <% end %>

        </p>
        <% if current_user.id == @user.id%>
        <%= link_to "Edit Profile", edit_user_path %>
        <%= link_to "Dindr Dates", invitations_path %>
        <%= link_to "Dindr Results", user_cuisines_path %>
        <% end %>
      </li>
    </ul>
  </div>

</div>


<!-- <div class="dates-pending">
<#%= render '/invitations/invitations' %>
</div> -->