config/routes.rb
Rails.application.routes.draw do


  resources :invitations, except: %i(new edit, show)

  resources :password_resets

  resources :restaurants, only: %i(index)

  root 'homes#index'

  get 'login' => 'sessions#new', :as => :login
  post 'create' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', :as => :logout
  get 'game' => 'pictures#index', :as => :game

  resources :homes, only: %i(index)
  #  will this work we shalll see
  resources :votes, except: %i(destroy)

    delete 'votes' => 'votes#destroy'


  resources :tags, except: %i(destroy edit update)
  resources :users, except: %i(destroy)
  resources :pictures, except: %i(index)

  namespace :admin do
    resources :pictures
  end

  namespace :user do
      resources :cuisines, only: %i(index show)
  end


end

app/views/layouts/_burger.html.erb
<!-- Burger for homepage  -->

<div class="navigation">
  <div class='hamburger'>
    <div class='menu-trigger'>
      <span id='home-burger'>Menu</span>
    </div>
  </div>

  <div id="nav-box">
    <% if current_user %>
      <ul id="nav-box-list">
        <li class="nav-box-list-items"><%= link_to "profile", user_path(current_user) %></li>
        <li class="nav-box-list-items"><%= link_to "game", game_path%></li>
        <li class="nav-box-list-items"><%= link_to "dindr dates", invitations_path%></li>
        <li class="nav-box-list-items"><%= link_to "results", user_cuisines_path%></li>
        <li class="nav-box-list-items"><%= link_to "logout", :logout, method: :delete %></li>

          <% if current_user.admin? %>
            <li class="nav-box-list-items"><%= link_to "view all pictures", admin_pictures_path %></li>
          <% end %>
    <% else %>
      <li class="nav-box-list-items"><%= link_to "sign up", new_user_path %></li>
      <li class="nav-box-list-items"> <%= link_to "login", 'javascript:;', class: 'modal-trigger' %>
    <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_burger_other_pages.html.erb
<div class="navigation">
  <div class='hamburger'>
    <div class='menu-trigger'>
      <span id='burger'>Menu</span>
    </div>
  </div>

  <div id="nav-box">
    <% if current_user %>
      <ul id="nav-box-list">
        <li class="nav-box-list-items"><%= link_to "profile", user_path(current_user) %></li>
        <li class="nav-box-list-items"><%= link_to "game", game_path%></li>
        <li class="nav-box-list-items"><%= link_to "dindr dates", invitations_path%></li>
        <li class="nav-box-list-items"><%= link_to "results", user_cuisines_path%></li>
        <li class="nav-box-list-items"><%= link_to "logout", :logout, method: :delete %></li>
          <% if current_user.admin? %>
        </br><li class="nav-box-list-items"><%= link_to "all pictures", admin_pictures_path %></li>
          <% end %>
    <% else %>
      <li class="nav-box-list-items"><%= link_to "sign up", new_user_path %></li>
      <li class="nav-box-list-items"> <%= link_to "login", 'javascript:;', class: 'modal-trigger' %>
    <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->

<footer class="footer-2" role="contentinfo">
  <div class="footer-logo">
    <%= link_to image_tag('dindr-littlered-d.png'), homes_path %>
  </div>


    <div class="footer-secondary-links">

      <ul>
        <li><a href="https://profiles.bitmaker.co/students/ariane-deschenes-foucher" target="_blank">
          Ariane D.
        </a></li>
        <li><a href="https://profiles.bitmaker.co/students/kim-oleiro" target="_blank">
          Kimberly O.
        </a></li>
        <li><a href="https://profiles.bitmaker.co/students/hou-tai-wong" target="_blank">
          Hou-Tai W.
        </a></li>
        <li><a href="https://profiles.bitmaker.co/students/dennis-choi" target="_blank">
          Dennis C.
        </a></li>
        <li><a href="https://profiles.bitmaker.co/students/mike-thai" target="_blank">
          Mike T.
        </a></li>
      </ul>
    </div>
</footer>

app/views/layouts/_homepage_navbar.html.erb
<!-- This is the navbar for all the pages aside from the homepage. -->

<div id="nav-2">

</div>

app/views/layouts/_modal.html.erb
<div class="modal">
  <div class="modal-open">
        <div class="modal-fade-screen">
          <div class="modal-inner">
            <div class="modal-close" for="modal-1"></div>
              <h1>Sign in</h1>

              <p class="modal-content">

          <%= form_tag create_path do %>

                <div class="field">
                  <%= label_tag :email %>
                  <%= text_field_tag :email, params[:email] %>
                </div>
                <div class="field">
                  <%= label_tag :password %>
                  <%= password_field_tag :password %>
                </div>
                <div class="action" id="login-submit">
                  <%= submit_tag :Submit %>
                </div>

              <% end %>

              <div class="center-me">
                <%= link_to 'Sign up', new_user_path, class: "reset-pass-link" %> | <%= link_to 'Reset your password', password_resets_path, class: "reset-pass-link"%>
              </div>
          </p>
        </div>
      </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!-- This is the navbar for all the pages aside from the homepage. -->

<div id="nav-3">

    <% if current_user %>
    <li class="nav-item" id="home-link">
        <%= link_to image_tag('dindr-littlered-d.png'), homes_path %>
      </li>

    <li class="nav-item"></li>
    <li class="nav-item"></li>
    <li class="nav-item"></li>
    <li class="nav-item"></li>
    <li class="nav-item"><%= render 'layouts/burger_other_pages' %></li>

    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dindr</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Figaro.env.google_maps_api_key}", async: true, defer: true %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= render 'layouts/navbar' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>

</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dindr</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'homes' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/burger' %>
  <%= render 'layouts/homepage_navbar' %>
  <%= render 'layouts/modal' %>
<%= yield %>
  <%= render 'layouts/footer' %>
</body>



</html>